// This file is automatically generated. Any changes may be lost.
// The following declarations describes all resources that might be loaded dynamically.

// Brush Aliases

// CSS Extensions
Syntax.styles["jquery.syntax.layout.list"] = ["public/base/jquery.syntax.layout.list.css"];
Syntax.styles["jquery.syntax.layout.inline"] = ["public/base/jquery.syntax.layout.inline.css", "public/modern/jquery.syntax.layout.inline.css"];
Syntax.styles["jquery.syntax.brush.xml"] = ["public/base/jquery.syntax.brush.xml.css"];
Syntax.styles["jquery.syntax.layout.plain"] = ["public/base/jquery.syntax.layout.plain.css", "public/modern/jquery.syntax.layout.plain.css"];
Syntax.styles["jquery.syntax.brush.assembly"] = ["public/base/jquery.syntax.brush.assembly.css"];
Syntax.styles["jquery.syntax.brush.bash-script"] = ["public/base/jquery.syntax.brush.bash-script.css"];
Syntax.styles["jquery.syntax.brush.applescript"] = ["public/base/jquery.syntax.brush.applescript.css"];
Syntax.styles["jquery.syntax.brush.css"] = ["public/base/jquery.syntax.brush.css.css"];
Syntax.styles["jquery.syntax.brush.clang"] = ["public/base/jquery.syntax.brush.clang.css"];
Syntax.styles["jquery.syntax.brush.turing"] = ["public/base/jquery.syntax.brush.turing.css"];
Syntax.styles["jquery.syntax.brush.python"] = ["public/base/jquery.syntax.brush.python.css"];
Syntax.styles["jquery.syntax.layout.editor"] = ["public/base/jquery.syntax.layout.editor.css", "public/modern/jquery.syntax.layout.editor.css"];
Syntax.styles["jquery.syntax.layout.fixed"] = ["public/base/jquery.syntax.layout.fixed.css"];
Syntax.styles["jquery.syntax.brush.protobuf"] = ["public/base/jquery.syntax.brush.protobuf.css"];
Syntax.styles["jquery.syntax.brush.bash"] = ["public/base/jquery.syntax.brush.bash.css"];
Syntax.styles["jquery.syntax.layout.table"] = ["public/base/jquery.syntax.layout.table.css"];
Syntax.styles["jquery.syntax.brush.html"] = ["public/base/jquery.syntax.brush.html.css"];
Syntax.styles["jquery.syntax.core"] = ["public/bright/jquery.syntax.core.css", "public/base/jquery.syntax.core.css"];
Syntax.styles["jquery.syntax.brush.apache"] = ["public/base/jquery.syntax.brush.apache.css"];
Syntax.styles["jquery.syntax.brush.ocaml"] = ["public/base/jquery.syntax.brush.ocaml.css"];
Syntax.styles["jquery.syntax.brush.diff"] = ["public/base/jquery.syntax.brush.diff.css"];

// Theme Configuration
Syntax.themes["bright"] = ["base"]
Syntax.themes["base"] = []
Syntax.themes["modern"] = ["base"]
