// This file is automatically generated. Any changes may be lost.
// The following declarations describes all resources that might be loaded dynamically.

// Brush Aliases

// CSS Extensions
Syntax.styles["jquery.syntax.layout.list"] = ["public/base/jquery.syntax.layout.list.css"];
Syntax.styles["jquery.syntax.layout.inline"] = ["public/base/jquery.syntax.layout.inline.css", "public/modern/jquery.syntax.layout.inline.css"];
Syntax.styles["jquery.syntax.layout.plain"] = ["public/base/jquery.syntax.layout.plain.css", "public/modern/jquery.syntax.layout.plain.css"];
Syntax.styles["jquery.syntax.layout.editor"] = ["public/base/jquery.syntax.layout.editor.css", "public/modern/jquery.syntax.layout.editor.css"];
Syntax.styles["jquery.syntax.layout.fixed"] = ["public/base/jquery.syntax.layout.fixed.css"];
Syntax.styles["jquery.syntax.layout.table"] = ["public/base/jquery.syntax.layout.table.css"];
Syntax.styles["jquery.syntax.core"] = ["public/bright/jquery.syntax.core.css", "public/base/jquery.syntax.core.css"];
Syntax.styles["jquery.syntax.brush.turing"] = ["public/base/jquery.syntax.brush.turing.css"];

// Theme Configuration
Syntax.themes["base"] = []
